name: tests-payments

on:
  pull_request:
    paths: #this job will be run only if the /auth directory changes
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
