name: tests-orders

on:
  pull_request:
    paths: #this job will be run only if the /auth directory changes
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
