name: tests-tickets

on:
  pull_request:
    paths: #this job will be run only if the /auth directory changes
      - "tickets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
